name: Tox

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Run tests on Python ${{ matrix.python-version }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version:
          - "3.10"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox>=4 tox-gh
      - name: Set up tox environment for Python ${{ matrix.python-version }}
        run: tox run -vv --notest
      - name: Run tests
        run: tox run

  static:
    name: Run static analysis tools
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        toxenv:
          - lint
          - mypy
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox>=4
      - name: Set up tox environment for ${{ matrix.toxenv }}
        run: tox run -vv --notest -e '${{ matrix.toxenv }}'
      - name: Run linters
        run: tox run -e '${{ matrix.toxenv }}'
